### ISSUE TITLE
flakefinder: include periodic jobs

### ISSUE THREAD

**Issue by rmohr** [kubevirt/project-infra#1076]
Right now we execute twice a day all tests in a periodic  job for every k8s version which we support.

They are executed on merged code and are therefore a perfect source for flakefinder, since there tests are always supposed to pass. Let's ensure that flakefinder picks them up.

**Comment by rmohr** [comment]
@dhiller @fgimenez FYI

**Comment by dhiller** [comment]
Should be relatively easy to do. We "just" need to add the logic to also apply the job result scanning to the run periodics.

**Comment by dhiller** [comment]
See #954 also (bigger scope though)
