### ISSUE TITLE
Clone CI jobs on release

### ISSUE THREAD

**Issue by rmohr** [kubevirt/project-infra#121]
/kind enhancement

Jobs on master should be copied and tied to a release branch when we do a release. Otherwise we will for instance try to run kubevirtci clusters which are not understood on release branches.

**Comment by rmohr** [comment]
We can probably leverage the [config-forker](https://github.com/kubernetes/test-infra/tree/59bfc5afff526c46b1c57d8f27e70f0026c0d83c/experiment/config-forker).

**Comment by cynepco3hahue** [comment]
We can also to use OpenShift approach the generate prow jobs for each release via https://github.com/openshift/ci-operator-prowgen

**Comment by rmohr** [comment]
that would mean that we have to use the `ci-operator`?

**Comment by cynepco3hahue** [comment]
In general, it generates prow jobs formatted to run under the ci-operator, but we can fork it and adapt to our need :smile:

**Comment by rmohr** [comment]
Hm, for the `config-forker` we only need annotations on jobs which we want to fork on every release ...

**Comment by cynepco3hahue** [comment]
@rmohr But I believe jobs will change from release to release, so you will need each time update this annotations no?

**Comment by rmohr** [comment]
@cynepco3hahue at the time of the release they are exactly in the shape which is needed for both: master and the new release branch. Then they will diverge.

**Comment by davidvossel** [comment]
> Jobs on master should be copied and tied to a release branch when we do a release. Otherwise we will for instance try to run kubevirtci clusters which are not understood on release branches.

is there a way to introduce a new ci lane and have it skip running on certain branches? so when you add a new ci lane, you'd just tell it to skip release branches <= current release branch. 

also, is there a way we can indicate that a ci lane is being skipped by having a catch all function that fast exits with a specific message/error code when the provider isn't recognized?

not having to manage forked configs would be nice.

**Comment by rmohr** [comment]
> is there a way to introduce a new ci lane and have it skip running on certain branches? so when you add a new ci lane, you'd just tell it to skip release branches <= current release branch.

In principle regex is supported for branch selection. Not sure if `<=` could be expressed with that. I would just say that all new lanes are tied to master and that the config-forker should just copy them on every release.

> not having to manage forked configs would be nice.

I would actually prefer forks. It is very transparent. My experience tells me that once you don't permanently switch the CI system itself (which we did quite often now), you don't have to change much on the older configs.

**Comment by davidvossel** [comment]
> I would actually prefer forks. It is very transparent. My experience tells me that once you don't permanently switch the CI system itself (which we did quite often now), you don't have to change much on the older configs.

A fork of this config means more moving parts when we cut release branches.

Did what did you think about the "fast exit and skip" when provider doesn't exist for a release branch?

**Comment by rmohr** [comment]
> Did what did you think about the "fast exit and skip" when provider doesn't exist for a release branch?

I would prefer to eliminate that we can run into this situation.

**Comment by slintes** [comment]
/remove-lifecycle rotten

;)
