### ISSUE TITLE
branch-protector failing with 404 on kubevirt/ovs-cin

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#1234]
Failing since around 24h now:
```
...
{"component":"branchprotector","error":"update kubevirt: update ovs-cni: update master from protected=true: get current branch protection: getting branch protection 404: Not Found","file":"prow/cmd/branchprotector/protect.go:143","func":"main.main","level":"error","msg":"0","severity":"error","time":"2021-05-18T11:57:56Z"}
{"component":"branchprotector","file":"prow/cmd/branchprotector/protect.go:145","func":"main.main","level":"fatal","msg":"Encountered 1 errors protecting branches","severity":"fatal","time":"2021-05-18T11:57:56Z"}
```

**Comment by dhiller** [comment]
FYI @fgimenez

**Comment by dhiller** [comment]
Looks like https://github.com/kubevirt/ovs-cni has moved to k8snetworkplumbingwg recently.

@phoracek do you know?

**Comment by dhiller** [comment]
Actions required:

- update references in config.yaml
- move jobs folder
- check for remaining references
- check that kubevirt-bot has enough access rights

**Comment by phoracek** [comment]
Hello, yes, we moved it yesterday.

All of that should have been covered by https://github.com/kubevirt/project-infra/pull/1224 and https://github.com/kubevirt/project-infra/pull/1229.

OVS CNI configuration is not managed by Prow, so we may need to set the branch protection manually. Is there a document describing what are the requirements?

**Comment by dhiller** [comment]
I figure the branch protector config needs to get removed then: https://github.com/kubevirt/project-infra/blob/master/github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml#L304

**Comment by phoracek** [comment]
Correct me if I'm wrong, but I see that we have kubemacpool protected https://github.com/kubevirt/project-infra/pull/1229 and it lives in the same org.

**Comment by phoracek** [comment]
Oh, but it is under a wrong subtree. Will post a fix.

**Comment by dhiller** [comment]
Or it needs to get moved to its own org session. Documentation for that is here: https://github.com/kubernetes/test-infra/tree/master/prow/cmd/branchprotector#branch-protection-documentation

**Comment by phoracek** [comment]
I posted a PR that should hopefully fix it. Thanks for raising this Daniel

**Comment by dhiller** [comment]
Thanks for the fast response! :+1:

**Comment by fgimenez** [comment]
> FYI @fgimenez

Thanks for the heads up! yep already opened this one https://github.com/kubevirt/project-infra/pull/1231 we can close it now that https://github.com/kubevirt/project-infra/pull/1235 is on its way
