### ISSUE TITLE
Run rook-ceph tests within the sig-storage lane

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#1305]
As acked by storage folks in the last community meeting we want to integrate the rook-ceph testing into the sig-storage lanes. This will make the rook-ceph lanes redundant, so we can then get rid of the old 1.17 lane that does rook-ceph testing afterwards.

This should be two steps:
1. PR1: integrate the rook-ceph testing into the sig-storage lanes
2. PR2: remove the standard rook-ceph lanes (there are some that do test other things, i.e. non-root, those need to get kept)

**Comment by awels** [comment]
We just need to make sure that we have another lane that does include the rook ceph storage. And I am assuming that will be this sig storage lane. If I am correct this is fine

**Comment by dhiller** [comment]
See kubevirt/kubevirt#5874 , kubevirt/project-infra#1370 , kubevirt/kubevirt#5931

/close
