### ISSUE TITLE
PRs on CNAO show unneeded lanes that should be skipped

### ISSUE THREAD

**Issue by RamLavi** [kubevirt/project-infra#1383]
The following lanes show on CNAO stable branch `release-0.53` PRs, although they [should skip](https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml#L167) these branches

example [PR](https://github.com/kubevirt/cluster-network-addons-operator/pull/914)
![lanes](https://user-images.githubusercontent.com/48101085/123540777-627ee580-d749-11eb-8201-fe926be15ae4.jpeg)

Moreover, these lanes have the a wrong `Required` label though they don't actually stop the PR from being merged (nor do they need to, but still the label is wrong)

Note: since this is not stopping the PRs from getting merged - this is not a high priority issue

**Comment by RamLavi** [comment]
Hey @fgimenez , we formerly talked about this a few weeks back, I'm just opening this issue for better tracking.

**Comment by fgimenez** [comment]
> Hey @fgimenez , we formerly talked about this a few weeks back, I'm just opening this issue for better tracking.

@RamLavi sure, thx for taking care and sorry for the late response, should be fixed with #1395
