### ISSUE TITLE
ADOPTERS automation

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/project-infra#1579]
KubeVirt is maintaining at least three lists of adopters.  I would like [kubevirt/kubevirt/ADOPTERS.md](https://github.com/kubevirt/kubevirt/blob/main/ADOPTERS.md) to be the master list which other lists consume.   I have a [pull req](https://github.com/kubevirt/kubevirt/pull/6385) in to refactor ADOPTERs to enable.

I would like a Prow script created that monitors file [kubevirt/kubevirt/ADOPTERS.md](https://github.com/kubevirt/kubevirt/blob/main/ADOPTERS.md).  If a change is detected then I would like the following to happen...
* Create GitHub Issue in kubevirt/kubevirt.github.io with appropriate kind/website and kind/enhancement labels saying "ADOPTERS change detected.  Please update website"
* Clone https://github.com/kubevirt/kubevirt.github.io
* Run [adopters.py](https://github.com/kubevirt/kubevirt.github.io/blob/master/_data/adopters.py)
* Create GitHub pull req in kubevirt/kubevirt.github.io

@dhiller What do you think?  Is this feasible?

**Comment by dhiller** [comment]
I think this is feasible, I was just wondering why we would need to create a GH issue? Merging the PR would already update the website, no? Maybe we can just ping a group of people that need to look at this PR?
