### ISSUE TITLE
Introduce a prowjob preset for git credentials

### ISSUE THREAD

**Issue by rmohr** [kubevirt/project-infra#1730]
We repeate pretty often the following:

 * Referencing the github token secret
 * Mounting the token from there
 * Specify the GIT_ASKPASS env variable

We can introduce a prowjob preset for that.

**Comment by brianmcarey** [comment]
A preset for github credentials has been added to all the relevant prowjobs.

@rmohr I think this issue can be closed?

**Comment by rmohr** [comment]
@brianmcarey thanks for taking care of it!

/close
