### ISSUE TITLE
flakefinder: allow hiding quarantined tests

### ISSUE THREAD

**Issue by rmohr** [kubevirt/project-infra#1874]
The quarantined tests are dominating the flakefinder report which makes it a little bit harder than necessary to identify current issues immediately. Maybe we can add a toggle to hide them. While these tests need to be fixed, they don't represent a new immediate issue which we need to act on.

**Comment by rmohr** [comment]
@dhiller FYI

**Comment by dhiller** [comment]
Sounds like a good idea IMHO.

/assign
