### ISSUE TITLE
dco links to non existing page

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#201]
![Screenshot from 2019-09-24 12-36-00](https://user-images.githubusercontent.com/809335/65504795-0e860380-dec8-11e9-973c-1eaae59477d0.png)

Target is [CONTRIBUTING.md](https://github.com/kubevirt/project-infra/blob/master/CONTRIBUTING.md)

Same issue goes for the other repositories.

/cc @fabiand 
/cc @rmohr

**Comment by iranzo** [comment]
In Webpage we've https://github.com/kubevirt/kubevirt.github.io/pull/434 that will rename the actual guidelines to CONTRIBUTING so will also cover this

**Comment by dhiller** [comment]
Obsolete, has been fixed
