### ISSUE TITLE
Onboard ARM cluster to set of workload clusters

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#2067]
As we want to run workloads for ARM as we do on prow workloads we need to onboard the ARM cluster as a workloads cluster. This means we need to enable scheduling of prow job pods on that cluster.

Details of what we need to do for that can be found in this document: https://github.com/kubevirt/project-infra/blob/main/docs/how-to-add-a-prow-cluster.md#how-can-we-add-a-new-cluster-to-run-ci-jobs

TODOs:
- [x] Onboard cluster to prow
- [x] make the bootstrap and deploy work for prow-arm-workloads
  - [ ] add creation of the required resources for running prowjobs there
  - [ ] check: should we integrate the cluster into the automatic deployment for
  - [ ] check: should we create a greenhouse cache instance and an image cache on the cluster?
  - [ ] TBD

**Comment by dhiller** [comment]
FYI @zlha

**Comment by dhiller** [comment]
FYI @zhlhahaha

**Comment by zhlhahaha** [comment]
Hi, Daniel, lots tasks are related to the CI testing infrastructure. What I can do here?

**Comment by zhlhahaha** [comment]
As multi-arch bootstrap image has been built, I am going to do the task.

**Comment by zhlhahaha** [comment]
Hi @dhiller , here is some information about the kubernetes cluster on Arm64
Kubernetes Version: 1.22.2
Cluster nodes: 1 bare metal server (Another server is waiting to add to the cluster, then we will have two nodes)
Server Information: Altra (80 Cores, 128GB RAM (8x 16GB), 1TB NVMe U.2 SSD, 1x 25GbE NIC)

Here are some questions:
 The current k8s cluster is deployed by @fgimenez , would kubevirt CI will keep maintaining the k8s cluster on Arm64? 
 The kubernetes version is 1.22.2, shall we upgrate it?

**Comment by zhlhahaha** [comment]
Onboard cluster to prow
https://github.com/kubevirt/project-infra/issues/2257
