### ISSUE TITLE
Flakefinder report not displaying successful runs of vgpu test

### ISSUE THREAD

**Issue by brianmcarey** [kubevirt/project-infra#2106]
The latest weekly flakefinder report [1] does not show any successful runs for the following test:
`[Serial][sig-compute]MediatedDevices with mediated devices configuration Should successfully passthrough a mediated device with a disabled display`

From testgrid[2] it can be seen that there are a large number of successful runs in the past week.

This makes it more difficult to judge the severity of the flakey test.

[1] https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2022-05-16-168h.html#row2
[2] https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-e2e-kind-1.23-vgpu

/cc @dhiller

**Comment by dhiller** [comment]
Please consider this: while testgrid looks at the test results of all runs, Flakefinder looks at the test results of **merged PRs** over the given interval. So some results may be missing here.

Can you point me to the succeded tests for SRIOV of merged PRs that are missing in the reports?

**Comment by brianmcarey** [comment]
Here are a couple of examples from recently merged PRs: 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7734/pull-kubevirt-e2e-kind-1.23-vgpu/1526208377208705024

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7724/pull-kubevirt-e2e-kind-1.23-vgpu/1525154241298042880

The test mentioned in this issue is part of the vgpu lanes.

**Comment by brianmcarey** [comment]
Thanks for taking a look @dhiller - your explanation has given me a better understanding of the report. It sounds good to me that it highlights the flakes.
