### ISSUE TITLE
Move default branch for kubevirt/csi-driver to main 

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#2204]
TODOs:
- [ ] create PRs that
  - [x] adjusts things in kubevirt/project-infra ([PR](https://github.com/kubevirt/project-infra/pull/2203))
    - [x] branches/skip_branches
    - [x] extra_refs.base_ref
    - [x] adjust call to git-pr.sh: [add parameter -T main](https://github.com/kubevirt/project-infra/blob/be0eadcf396ae0d10edaf216a8ef3e434f1ef0a6/github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml#L308)
    - [x] adjusts branch protection rules
    - [x] adjusts [default_branch in orgs.yaml](https://github.com/kubevirt/project-infra/blob/master/github/ci/prow-deploy/files/orgs.yaml#L433)
  - [x] ~adjust things for openshift-ci : look at openshift/release configs for the repository~
- [x] wait for acks, iterate over PR
- [x] change default branch to main ( see renaming:[ https://github.com/github/renaming](https://github.com/github/renaming))
- [x] merge PRs

**Comment by dhiller** [comment]
FYI @awels

**Comment by awels** [comment]
Thanks! much appreciated
