### ISSUE TITLE
The release-blocker seems to have issues identifying its bot name

### ISSUE THREAD

**Issue by rmohr** [kubevirt/project-infra#2242]
The release blocker plugin did not realize that kubevirt-bot added the label (so itself) and removed it again due to not allowing manually adding the label. Going from https://github.com/kubevirt/project-infra/pull/2241 provides more info.

**Comment by brianmcarey** [comment]
@xpivarc  I believe https://github.com/kubevirt/project-infra/pull/2243 fixed this issue?

**Comment by xpivarc** [comment]
/close
Fixed int #2243
