### ISSUE TITLE
build-multiarch-bootstrap-image timing out after 4 hours

### ISSUE THREAD

**Issue by brianmcarey** [kubevirt/project-infra#2252]
The `build-multiarch-bootstrap-image`  takes a very long time to complete since the addition of the arm64 builds [1]. This is due to reduced performance from emulation when building the arm64 images. The job has been seen to fail due to hitting the timeout limit of 4 hours [2]. 

We may have to look at building the arm64 images natively on the ARM cluster using a periodic job. 

[1] https://github.com/kubevirt/project-infra/pull/1149
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2055/build-multiarch-bootstrap-image/1559137945284251648

/cc @dhiller @zhlhahaha

**Comment by oshoval** [comment]
We need to consider moving to podman / buildah as well
wonder if it might be faster ? (it also has emulation however)

**Comment by brianmcarey** [comment]
As far as I can see the main increase is due to the emulation for the arm64 builds.
