### ISSUE TITLE
Add Prow build cluster prow-arm64-workloads

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/project-infra#2257]
As multiarch bootstrap image has been built, we can add Arm64 kubernetes cluster in to Prow.
[my-kubeconfig.zip](https://github.com/kubevirt/project-infra/files/9355892/my-kubeconfig.zip)

**Comment by zhlhahaha** [comment]
Hi would you mind to take a look this issue when you have time?
/assign @dhiller

**Comment by zhlhahaha** [comment]
Hi @dhiller @rmohr , here is some information about the kubernetes cluster on Arm64
Kubernetes Version: 1.22.2
Cluster nodes: 1 bare metal server (Another server is waiting to add to the cluster, then we will have two nodes)
Server Information: Altra (80 Cores, 128GB RAM (8x 16GB), 1TB NVMe U.2 SSD, 1x 25GbE NIC)

Here are some questions:
1. The current k8s cluster is deployed by @fgimenez . As I see Federico in the emeritus_approvers list, who should I contact to maintain Arm64 servers?
2. The kubernetes version is 1.22.2, shall we upgrade it?

**Comment by zhlhahaha** [comment]
Hi @dhiller @brianmcarey 
Any comments?

**Comment by zhlhahaha** [comment]
Hi @dhiller @brianmcarey 
I have setup 2 kubernetes clusters for CI testing. here is the kubeconfig file. As gpg file is not allowed to upload to github, I compress them into zip file.
 
[Arm64-Server1-kubeconfig.zip](https://github.com/kubevirt/project-infra/files/9757135/Arm64-Server1-kubeconfig.zip)
[Arm64-Server2-kubeconfig.zip](https://github.com/kubevirt/project-infra/files/9757136/Arm64-Server2-kubeconfig.zip)

**Comment by brianmcarey** [comment]
@zhlhahaha I think we can close this as the clusters have been added to prow and jobs can be scheduled to the clusters. 

/close
