### ISSUE TITLE
Add branch protection for hostpath-provisioner-operator

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#234]
Regarding the [branch protection configuration](https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/config.yaml#L96) @awels and @aglitke should decide what checks for merging they need and then we can enable them here.

See configuration for feasible examples.

/cc @fabiand

**Comment by awels** [comment]
@dhiller We need continuous-integration/travis-ci/pr

**Comment by awels** [comment]
So there are 2 hostpath-provisioner repos, hostpath-provisioner AND hostpath-provisioner-operator. Both need the same.
