### ISSUE TITLE
kubevirtci bumper missing variants of kubevirtci providers

### ISSUE THREAD

**Issue by brianmcarey** [kubevirt/project-infra#2340]
The automated kubevirtci bumper which bumps the minor versions of the kubevirtci providers is currently missing variants of the major version providers such as `1.24-psa` & `1.24-ipv6`. The automation should be able to handle the bumping of these variants too.

An example automated PR: https://github.com/kubevirt/kubevirtci/pull/877

**Comment by dhiller** [comment]
That is because when we created the automation we just agreed on doing the bumps for the specialized providers manually. But a good idea to extend that to the others if that is easy to do :+1:

**Comment by oshoval** [comment]
since psa doesnt have dedicated lane anymore and ipv6 will soon as well
i think we can close this issue

**Comment by brianmcarey** [comment]
Yes I think you are right - the reduction in providers will get rid of this problem. 

/close

**Comment by brianmcarey** [comment]
We have this problem again now with the introduction of the 1.26-centos-9 provider.
