### ISSUE TITLE
CI isn't triggered for the test-benchmarks repo

### ISSUE THREAD

**Issue by alicefr** [kubevirt/project-infra#2399]
I just tried to open a [first PR](https://github.com/kubevirt/test-benchmarks/pull/1) for the repo [test-benchmarks](https://github.com/kubevirt/test-benchmarks) and the CI job  with the [unit tests](https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/test-benchmarks/test-benchmarks-presubmits.yaml#L23). 

Have I missed something in the setup of the CI?

**Comment by dhiller** [comment]
Just as a note for further us - here's the docs on what to do when we want to enable prow CI: https://github.com/kubevirt/community/blob/main/docs/add-merge-automation-to-your-repository.md

**Comment by dhiller** [comment]
@lyarwood FYI, maybe you need this also: https://github.com/kubevirt/community/blob/main/docs/add-merge-automation-to-your-repository.md

**Comment by lyarwood** [comment]
> @lyarwood FYI, maybe you need this also: https://github.com/kubevirt/community/blob/main/docs/add-merge-automation-to-your-repository.md

ACK yeah thanks I noticed it yesterday in https://github.com/kubevirt/common-instancetypes/pull/4#issuecomment-1300174624 and have a draft change ready to go, I'll follow up today.
