### ISSUE TITLE
Update release notes script for new release cadence

### ISSUE THREAD

**Issue by aburdenthehand** [kubevirt/project-infra#2576]
With the change in release cadence, we can expect much larger release notes per release. As such, it would be good to automatically filter these release notes into categories, and provide a staging period of 1-2 weeks for manual editing/formatting where necessary before they are published with the KubeVirt release.

This PR describes the usage of labels used to categorise:
https://github.com/kubevirt/kubevirt/pull/8752
Using kind/ labels to filter these into categories, followed by sig/ labels to group these release notes within the categories. 

We currently have a script that automatically takes the release notes from relevant PRs and collates them. We just need to adjust the existing process to include filtering (afaik)
@davidvossel, can you please add the details that we talked about offline?

See also the discussion on the mailing list from last year:
https://groups.google.com/g/kubevirt-dev/c/FvtVEAIVjo0/m/02-Fj5tKCQAJ?hl=en

**Comment by davidvossel** [comment]
Hey, So for the better categorized release notes, the release tool will need to be updated to generate those notes. That logic is found here [1].

The release tool already has logic that inspects every PR [2] for a release note. We need is to tap into that existing information and also categorize the release nodes by certain labels which are in the PR. We're already retrieving that label information as part of retrieving the PRs, the labels just are not being used to influence the release notes yet.

1. https://github.com/kubevirt/project-infra/blob/b0392015501434380f4e7f3920dc549515ca485d/releng/release-tool/release-tool.go#L78 
2. https://github.com/kubevirt/project-infra/blob/b0392015501434380f4e7f3920dc549515ca485d/releng/release-tool/release-tool.go#L351

**Comment by aburdenthehand** [comment]
We currently have a script in the user-guide repo that has been historically used to generate the release notes (RNs) for kubevirt.io/docs/release-notes, and it uses `git show -v <tag>`. This script is now broken (pulls beta and needs to be manually edited), but also the git show command ignores the formatting from the tag, and also might include other RNs, intended for subsequent z-stream (iiuc). 

Using the script to generate a markdown file with the filtered and formatted RNs would provide us with a consistent and easily editable (while also being version controlled) source for RNs, and one that would be easy to duplicate in the user-guide.

**Comment by aburdenthehand** [comment]
https://github.com/kubevirt/project-infra/issues/2946#issuecomment-1695766019 
Good suggestion to include which k8s versions are supported for the new release at the top of the release notes page
