### ISSUE TITLE
rehearse-plugin: release branch job rehearsals run against latest on main

### ISSUE THREAD

**Issue by brianmcarey** [kubevirt/project-infra#2783]
When making changes to release branch job configs like in https://github.com/kubevirt/project-infra/pull/2765 - the rehearsal jobs appear to run against the latest on the main branch of that repo. 

The following rehearsal job of `pull-kubevirt-e2e-k8s-1.24-ipv6-sig-network-0.58` fails due to the cluster provider not being available. 
 https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2765/rehearsal-pull-kubevirt-e2e-k8s-1.24-ipv6-sig-network-0.58/1660628749260951552#1:build-log.txt%3A47

This cluster provider is available on the 0.58 branch:
https://github.com/kubevirt/kubevirt/tree/release-0.58/cluster-up/cluster/k8s-1.24-ipv6

This prevents us from accurately testing changes to release branch job configs.

**Comment by dhiller** [comment]
My suspicion is that the shas for creating the job are taken from the wrong branch (i.e. the PR that modifies the jobs). They should be constructed from the Branches struct. Not sure why this is even working ATM.
