### ISSUE TITLE
update amd-sev-cluster.md

### ISSUE THREAD

**Issue by Nitishupkr** [kubevirt/project-infra#2820]
update  the software details with the latest updated version 
![hbnjmk,l;](https://github.com/kubevirt/project-infra/assets/95420063/fce2934e-9b9a-4ef4-8087-d34a931967f0)

if it is valid then give your feedback 
i will rise PR for this

**Comment by brianmcarey** [comment]
Hi @Nitishupkr - thanks for raising this issue - I am not aware of any software updates on the cluster? These details are to reflect what is currently running in the cluster.

**Comment by Nitishupkr** [comment]
hey i want to solve this issue can u assign it to me

**Comment by brianmcarey** [comment]
@Nitishupkr - I checked on the system and the information is still correct. 

/close
