### ISSUE TITLE
Add in_repo_config to prow

### ISSUE THREAD

**Issue by qinqon** [kubevirt/project-infra#283]
Prow supports in repo jobs config adding .prow.yaml at project root, to do so the plugin https://github.com/kubernetes/test-infra/blob/master/prow/inrepoconfig.md has to be activated.

**Comment by dhiller** [comment]
IDK, I remember we had a discussion about that. I think the outcome was that we rather wanted to keep the config in this repo and use OWNERS instead? I have no strong opinion on that myself, I tend to rather have configuration about jobs together with the project that it affects.

@qinqon @rmohr opinions?

**Comment by qinqon** [comment]
I have same feature at my previous team, from a user perspective is super nice to test at same PR product changes and job changes, so you can iterate on both atomically, but it's also true that we open the pandora box there and we will need to monitor prow server to heck if someone is doing something really bad at their project and we don't have dedicated CI team.

**Comment by qinqon** [comment]
Maybe we can activate just for kubevirtci check jobs it's very infra thing and kind of make sense since it goes hand by hand with project-infra

**Comment by dhiller** [comment]
> Maybe we can activate just for kubevirtci check jobs it's very infra thing and kind of make sense since it goes hand by hand with project-infra

That makes sense!

**Comment by rmohr** [comment]
I don't think that we are in a good position to distribute the jobs. We have a lot of infra specific workarounds and like mentioned no ci team. I would prefer to enable o something like pj-rehearsal or finish the plugins WIP from Daniel to allow testing the jobs in project-infra PRs.

**Comment by qinqon** [comment]
Testing pro at project-infra PR would be good too, closing this issue.

**Comment by qinqon** [comment]
We don't have the team, resources to do so, we have use the other way around running jobs at project-infra PRs.

**Comment by dhiller** [comment]
FTR: see also kubevirt/project-infra#303
