### ISSUE TITLE
Clean environment before building in jenkins

### ISSUE THREAD

**Issue by rmohr** [kubevirt/project-infra#29]
I see reports like:

```
[xUnit] [ERROR] - Test reports were found but not all of them are new. Did all the tests run?
  * /var/lib/swarm/workspace/kubevirt-functional-tests-vagrant-dev/junit.xml is 20 hr old
```
in our jobs.

Everything we cache is cached in docker. We can simply clean the whole workspace before we start a build.

**Comment by cynepco3hahue** [comment]
@rmohr hm I think you can see such thing only if Junit reporter failed to generate a new report, I think it happens when you abort Jenkins job
So I do not sure it has effect on something

**Comment by rmohr** [comment]
> So I do not sure it has effect on something

Good, so we should then simply clean up the workspace to not generate meaningless errors.

**Comment by cynepco3hahue** [comment]
I do not sure that we will node receive the error about lack of `junit.xml` file in this case :smile: 
But let me check.

**Comment by cynepco3hahue** [comment]
ok we can use plugin https://wiki.jenkins.io/display/JENKINS/Workspace+Cleanup+Plugin

**Comment by rmohr** [comment]
> I do not sure that we will node receive the error about lack of junit.xml file in this case 
> But let me check.

ha true. :+1:  Still I would prefer to clean up.
