### ISSUE TITLE
rehearse-plugin: deny rehearse for non lgtm PRs

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#2920]
We should discuss denying rehearsals if the PR doesn't yet have a `lgtm` label.

When working on https://github.com/kubevirt/project-infra/pull/2919 @Barakmor1 mentioned that a KubeVirt community member might trigger some potentially destructive action through the rehearsal of a job. Looking at whether the `lgtm` label is present before actually running the job prohibits this.

Also the `lgtm` label is removed on any push, so no change will go unnoticed with at least two pair of eyes having looked at it.

TODOs:
* [ ] Verify that PR has `lgtm`
* [ ] If it hasn't, add comment that it is required to have `lgtm`
* [ ] Add documentation that rehearsal requires PRs to have `lgtm`

**Comment by dhiller** [comment]
@brianmcarey WDYT?

**Comment by brianmcarey** [comment]
This sounds good I guess we can't use the `ok-to-test` label because the author of the PR would still be able to add that label and create rehearsal jobs.

**Comment by dhiller** [comment]
One drawback is that the convenience of rehearsing changes without involving anyone else would go away, since users would always need to involve another person to get an lgtm after a change.

Also we discussed that KubeVirt org members should be trusted in not doing any harm.
