### ISSUE TITLE
Generate k8s support matrix per version

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#2946]
Users want to know which k8s versions are supported by which k6t version.

We can generate a support matrix document from parsing the job definitions per version in project-infra. Output mock:

| k6t version | k8s-1.19 | ... | k8s-1.25| k8s-1.26 | k8s-1.27| k8s-1.28 | source |
|-------------|---|---|---|---|---|---|---|
| main | - | ... | - | x | x | x | [job config](https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml) |
| 1.0 | - | ... | x | x | x | - | [job config](https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml) |

> > We are confused if 0.58 supports k8s 1.25.
> ...
> > It will be really helpful if you can provide the documentation that specifies the compatibility matrix for various versions.
> 
> Yeah, that is now missing. Agree, it would be useful to have such a matrix.

_Originally posted by @xpivarc in https://github.com/kubevirt/kubevirt/issues/8482#issuecomment-1477469520_

**Comment by aburdenthehand** [comment]
That sounds perfect. Thanks for looking into this, Daniel!
We have an issue open in sig-release: https://github.com/kubevirt/sig-release/issues/6
Would we be able to generate this matrix in that repo?

**Comment by dhiller** [comment]
> That sounds perfect. Thanks for looking into this, Daniel! We have an issue open in sig-release: [kubevirt/sig-release#6](https://github.com/kubevirt/sig-release/issues/6) Would we be able to generate this matrix in that repo?

Makes sense. I'd put the document into https://github.com/kubevirt/sig-release/tree/main/releases
WDYT?

**Comment by dhiller** [comment]
Looking at https://github.com/kubevirt/kubevirt/blob/b0bbb1d25d1f841c8d06413a4446d3f699b5f9a5/docs/release.md?plain=1#L52 and then at at https://kubernetes.io/releases/
I understand that we would build the support matrix using the latest 4 k8s versions as a base set, right?

So, when building a support matrix I would include all KubeVirt releases supporting k8s versions that are not yet EOL, and only those k8s versions which are not yet EOL.

**Comment by dhiller** [comment]
> Looking at https://github.com/kubevirt/kubevirt/blob/b0bbb1d25d1f841c8d06413a4446d3f699b5f9a5/docs/release.md?plain=1#L52 and then at at https://kubernetes.io/releases/ I understand that we would build the support matrix using the latest 4 k8s versions as a base set, right?
> 
> So, when building a support matrix I would include all KubeVirt releases supporting k8s versions that are not yet EOL, and only those k8s versions which are not yet EOL.

Or, to make it easier, for all KubeVirt versions released at most one year from now.

**Comment by aburdenthehand** [comment]
Yeah, that makes sense. Probably more sensible than what I was thinking with leaving it in https://github.com/kubevirt/sig-release/tree/main/
I'm not opposed but I'm not following why we would need 4 versions. If we only support 3 versions of KubeVirt against 3 versions of k8s at any given time. ie after our next release we would have:

|KubeVirt version|K8s 1.26 | k8s 1.27 | 1.28 |
|----|----|----|----|
| v0.59 | x | - | - |
| v1.0 | x | x | -|
| v1.1 | x | x | x |

And then 0.59 and 1.26 roll off at the release of 1.2 and 1.29 respectively.

**Comment by dhiller** [comment]
That's my first result:

| KUBEVIRT VERSION | 1.27 | 1.26 | 1.25 | (1.24) | (1.23) | (1.22) | (1.21) | (1.20) | (1.19) |
|------------------|------|------|------|--------|--------|--------|--------|--------|--------|
| main             | ✓    | ✓    | ✓    | -      | -      | -      | -      | -      | -      |
|              1.0 | ✓    | ✓    | ✓    | -      | -      | -      | -      | -      | -      |
|             0.59 | -    | ✓    | ✓    | (✓)    | -      | -      | -      | -      | -      |
|             0.58 | -    | -    | -    | (✓)    | (✓)    | (✓)    | -      | -      | -      |
|             0.57 | -    | -    | -    | (✓)    | (✓)    | (✓)    | -      | -      | -      |
|             0.56 | -    | -    | -    | (✓)    | (✓)    | (✓)    | -      | -      | -      |
|             0.55 | -    | -    | -    | -      | (✓)    | (✓)    | -      | -      | -      |
|             0.54 | -    | -    | -    | -      | (✓)    | (✓)    | (✓)    | -      | -      |
|             0.53 | -    | -    | -    | -      | (✓)    | (✓)    | (✓)    | -      | -      |
|             0.52 | -    | -    | -    | -      | (✓)    | (✓)    | (✓)    | -      | -      |
|             0.51 | -    | -    | -    | -      | (✓)    | (✓)    | (✓)    | -      | -      |
|             0.50 | -    | -    | -    | -      | (✓)    | (✓)    | (✓)    | -      | -      |
|             0.49 | -    | -    | -    | -      | (✓)    | (✓)    | (✓)    | -      | -      |
|             0.48 | -    | -    | -    | -      | -      | (✓)    | (✓)    | (✓)    | -      |
|             0.47 | -    | -    | -    | -      | -      | -      | (✓)    | (✓)    | -      |
|             0.46 | -    | -    | -    | -      | -      | -      | (✓)    | (✓)    | -      |
|             0.45 | -    | -    | -    | -      | -      | -      | (✓)    | (✓)    | (✓)    |
|             0.44 | -    | -    | -    | -      | -      | -      | -      | (✓)    | (✓)    |
|             0.43 | -    | -    | -    | -      | -      | -      | -      | -      | (✓)    |
|             0.42 | -    | -    | -    | -      | -      | -      | -      | -      | (✓)    |
|             0.41 | -    | -    | -    | -      | -      | -      | -      | -      | (✓)    |

Probably a bit too much, right?

**Comment by dhiller** [comment]
@aburdenthehand please note that this is a view reflecting how our current testing is configured, not how it should be. Therefore the main branch has currently 1.27-1.25 as supported k8s versions.

**Comment by dhiller** [comment]
Alternatively we could just generate the table from a yaml where the new _desired_ state is added, i.e.

```yaml
schedules:
  - release: 1.1
    supported-k8s-versions:
    - 1.26
    - 1.27
    - 1.28
  - release: 1.0
    supported-k8s-versions:
    - 1.25
    - 1.26
    - 1.27
```

That then would yield a table like you described.

Please see [k8s/release schedule.yaml](https://raw.githubusercontent.com/kubernetes/website/main/data/releases/schedule.yaml)

**Comment by dhiller** [comment]
# KubeVirt to Kubernetes version support matrix

| KubeVirt version | 1.27      | 1.26      | 1.25      | 1.24[^1]  | 1.23[^1]  | 1.22[^1]  | 1.21[^1]  | 1.20[^1]  | 1.19[^1]  |
|-------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
| 1.0  | ✓      | ✓      | ✓      | -      | -      | -      | -      | -      | -      |
| 0.59  | -      | ✓      | ✓      | ✓[^1]  | -      | -      | -      | -      | -      |
| 0.58  | -      | -      | -      | ✓[^1]  | ✓[^1]  | ✓[^1]  | -      | -      | -      |
| 0.57  | -      | -      | -      | ✓[^1]  | ✓[^1]  | ✓[^1]  | -      | -      | -      |
| 0.56  | -      | -      | -      | ✓[^1]  | ✓[^1]  | ✓[^1]  | -      | -      | -      |
| 0.55  | -      | -      | -      | -      | ✓[^1]  | ✓[^1]  | -      | -      | -      |
| 0.54  | -      | -      | -      | -      | ✓[^1]  | ✓[^1]  | ✓[^1]  | -      | -      |
| 0.53  | -      | -      | -      | -      | ✓[^1]  | ✓[^1]  | ✓[^1]  | -      | -      |
| 0.52  | -      | -      | -      | -      | ✓[^1]  | ✓[^1]  | ✓[^1]  | -      | -      |
| 0.51  | -      | -      | -      | -      | ✓[^1]  | ✓[^1]  | ✓[^1]  | -      | -      |
| 0.50  | -      | -      | -      | -      | ✓[^1]  | ✓[^1]  | ✓[^1]  | -      | -      |
| 0.49  | -      | -      | -      | -      | ✓[^1]  | ✓[^1]  | ✓[^1]  | -      | -      |
| 0.48  | -      | -      | -      | -      | -      | ✓[^1]  | ✓[^1]  | ✓[^1]  | -      |
| 0.47  | -      | -      | -      | -      | -      | -      | ✓[^1]  | ✓[^1]  | -      |
| 0.46  | -      | -      | -      | -      | -      | -      | ✓[^1]  | ✓[^1]  | -      |
| 0.45  | -      | -      | -      | -      | -      | -      | ✓[^1]  | ✓[^1]  | ✓[^1]  |
| 0.44  | -      | -      | -      | -      | -      | -      | -      | ✓[^1]  | ✓[^1]  |
| 0.43  | -      | -      | -      | -      | -      | -      | -      | -      | ✓[^1]  |
| 0.42  | -      | -      | -      | -      | -      | -      | -      | -      | ✓[^1]  |
| 0.41  | -      | -      | -      | -      | -      | -      | -      | -      | ✓[^1]  |


[^1]: Kubernetes version has reached EOL

@aburdenthehand WDYT?

**Comment by aburdenthehand** [comment]
@dhiller It definitely highlights the difference! But it is a bit noisy, particularly the litany of returns in the footnote. Could we change the ✓s in the unsupported cells to 'EOL' or something to avoid the footmarks? And then we can have a note under the table to explain that 'EOL' shows the version of KubeVirt that was built to be used for those versions of K8s but neither are supported and are included here for academic reasons. Or words to that effect. 
While I see the point in keeping older versions to help out some of our users, I think we do need to draw the line somewhere. 1.22 is coming up to 1 year since it went EOL. To me that seems like a reasonable cut-off but happy to negotiate :)

**Comment by dhiller** [comment]
# KubeVirt to Kubernetes version support matrix

| KubeVirt version | 1.27               | 1.26               | 1.25               | 1.24<sup>EOL</sup> | 1.23<sup>EOL</sup> | 1.22<sup>EOL</sup> |
|------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
|              1.0 | ✓                  | ✓                  | ✓                  | -                  | -                  | -                  |
|              0.59 | -                  | ✓                  | ✓                  | EOL                | -                  | -                  |
|              0.58 | -                  | -                  | -                  | EOL                | EOL                | EOL                |
|              0.57 | -                  | -                  | -                  | EOL                | EOL                | EOL                |
|              0.56 | -                  | -                  | -                  | EOL                | EOL                | EOL                |
|              0.55 | -                  | -                  | -                  | -                  | EOL                | EOL                |
|              0.54 | -                  | -                  | -                  | -                  | EOL                | EOL                |
|              0.53 | -                  | -                  | -                  | -                  | EOL                | EOL                |
|              0.52 | -                  | -                  | -                  | -                  | EOL                | EOL                |
|              0.51 | -                  | -                  | -                  | -                  | EOL                | EOL                |
|              0.50 | -                  | -                  | -                  | -                  | EOL                | EOL                |
|              0.49 | -                  | -                  | -                  | -                  | EOL                | EOL                |
|              0.48 | -                  | -                  | -                  | -                  | -                  | EOL                |


Note: _EOL_ means that the Kubernetes version was supported by KubeVirt but has reached end of life. See [Kubernetes releases](https://kubernetes.io/releases/) for more details

**Comment by aburdenthehand** [comment]
@dhiller - That looks wonderful to me. 
Thank you!

**Comment by dhiller** [comment]
ack. Will finalize the PR then by creating a job that generates/updates a document inside the sig-release/releases path.

**Comment by aburdenthehand** [comment]
@vasiliy-ul @xpivarc @fabiand FYI

**Comment by vasiliy-ul** [comment]
https://github.com/kubevirt/project-infra/issues/2946#issuecomment-1695766019 - this looks awesome :+1: 

Could we also get a small table/list with the supported Kubernetes version on the release notes page? So if I go e.g. to https://github.com/kubevirt/kubevirt/releases/tag/v1.0.0 I am able to see right away what this particular release has been tested on.

**Comment by xpivarc** [comment]
I think I fear that in the future my monitor will be not enough to see the whole table ;) 

In parallel, I would propose to add 2 more things:
1. Let's include in the schedule the "wanter" to support versions
2. Let's keep a table only with the supported Kubernetes version and related Kubevirt versions to it.

I am asking for the latter to steer the users rather to a supported version than the whole picture.

**Comment by dhiller** [comment]
Actually I have stripped down the information already:
* only the last three k8s EOL versions are shown, regardless of how many are there, which results in 6 k8s versions shown at any time
* all the K6t versions that don't support any of the former K8s versions are removed from the data set

This is a reasonable compromise between showing all versions and only the latest three. WDYT?

**Comment by dhiller** [comment]
> I think I fear that in the future my monitor will be not enough to see the whole table ;)
> 
> In parallel, I would propose to add 2 more things:
> 
> 1. Let's include in the schedule the "wanted" to support versions. And also add them to release/tag
> 2. Let's keep a table only with the supported Kubernetes version and related Kubevirt versions to it.
> 
> I am asking for the latter to steer the users rather to a supported version than the whole picture.

I am not against doing both items you have requested, although I think we should finish this one first, as it brings value right now, since we don't have anything to this regard yet and users have requested it.

WDYT?

**Comment by xpivarc** [comment]
> I am not against doing both items you have requested, although I think we should finish this one first, as it brings value right now, since we don't have anything to this regard yet and users have requested it.
> 
> WDYT?

I agree.

**Comment by dhiller** [comment]
I'll create a follow up issue with the remaining items, like @vasiliy-ul and @xpivarc mentioned.

WRT to [the initial PR](https://github.com/kubevirt/project-infra/pull/2948), are there any objections about merging it?

**Comment by xpivarc** [comment]
> I'll create a follow up issue with the remaining items, like @vasiliy-ul and @xpivarc mentioned.
> 
> WRT to [the initial PR](https://github.com/kubevirt/project-infra/pull/2948), are there any objections about merging it?

WDYT @fabiand @aburdenthehand  ?

**Comment by aburdenthehand** [comment]
I think it's wonderful! :) 
I left a question on the implementation PR but I don't think it should block merge.
