### ISSUE TITLE
Arm64 CI: prow-arm64-workloads was down because of DNS attack

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/project-infra#3079]
I received an email form the Arm64 server provider. The server got dns attack, and the network is down.
```
Per our NetOps team, The traffic came from multiple sources and destined to the port UDP/53 (DNS), they suspect that it's a DNS amplification attack.

- Traffic spikes:
07:04 UTC -->218 Gbps
07:07 UTC -->81 Gbps
```

They suggest me to redeploy the server, then we will receive a new IP. This can avoid attack from outside. I will re-deploy the server today. Do we need to migrate the e2e tests to the cluster `prow-arm64-workloads-2`
@dhiller @xpivarc @brianmcarey

**Comment by zhlhahaha** [comment]
Hi, I have re-deployed the server, would you mind to replace the kubeconfig for the cluster `prow-arm64-workloads`.
[kubevirt-ci-arm64-01-kubeconfig.gpg.zip](https://github.com/kubevirt/project-infra/files/13406070/kubevirt-ci-arm64-01-kubeconfig.gpg.zip)

**Comment by zhlhahaha** [comment]
I am encrypt the config according to https://github.com/kubevirt/project-infra/blob/main/docs/how-to-add-a-prow-cluster.md

**Comment by zhlhahaha** [comment]
Hi @dhiller , I have encrypt the file with new key, please give it a try when you have time. Thanks!
[kubevirt-ci-arm64-01-kubeconfig.gpg.zip](https://github.com/kubevirt/project-infra/files/13414448/kubevirt-ci-arm64-01-kubeconfig.gpg.zip)

**Comment by zhlhahaha** [comment]
@dhiller 
[kubevirt-ci-arm64-02-kubeconfig.gpg.zip](https://github.com/kubevirt/project-infra/files/13450100/kubevirt-ci-arm64-02-kubeconfig.gpg.zip)

**Comment by dhiller** [comment]
Jobs are running again, I think we are good now.

/close

@zhlhahaha please reopen if you disagree

**Comment by zhlhahaha** [comment]
> Jobs are running again, I think we are good now.
> 
> /close
> 
> @zhlhahaha please reopen if you disagree

Thanks, Daniel!
