### ISSUE TITLE
Add Prow build cluster prow-s390x-workloads

### ISSUE THREAD

**Issue by ibm-jitendra** [kubevirt/project-infra#3140]
@brianmcarey , @dhiller ,

As discussed, we are able to create an external single node k8s cluster on s390x cloud VM instance based
on below instruction:
https://github.com/kubevirt/kubevirtci/tree/main/cluster-up/cluster/external

Hereby i'm attching encrypted kubeconfig for the same.
Can we add s390x kubernetes cluster in to Prow ?

[s390x-kubeconfig.tar.gz](https://github.com/kubevirt/project-infra/files/13744145/s390x-kubeconfig.tar.gz)

**Comment by brianmcarey** [comment]
Thanks for this @ibm-jitendra - I will take a look

/assign

**Comment by ibm-jitendra** [comment]
@brianmcarey 
Made necessary changes in kubeconfig and hence uploading new kubeconfig file.
[s390x-kubeconfig.tar.gz](https://github.com/kubevirt/project-infra/files/13979346/s390x-kubeconfig.tar.gz)

**Comment by brianmcarey** [comment]
This cluster has been added to the prow-kubeconfig and should be available with cluster name: `s390x-prow-virtual`

**Comment by brianmcarey** [comment]
The cluster has been onboarded to the kubevirt prow. 

Closing this issue. 

/close
