### ISSUE TITLE
shared-images-controller: evaluate whether we should cache kubevirtci images for the release branches

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#3144]
ATM we only [cache the kubevirtci images used in main branch of kubevirt/kubevirt](https://github.com/kubevirt/project-infra/blob/main/images/shared-images-controller/main.go#L27). 

We should evaluate whether it makes sense to also cache the images from the release branches.

I.e. common-instancetypes also uses kubevirtci and references the version from the kubevirt/kubevirt release branch.

**Comment by dhiller** [comment]
FYI @0xFelix @brianmcarey

**Comment by dhiller** [comment]
@brianmcarey I think this has proven to not be necessary, so we can keep this closed. WDYT?

**Comment by 0xFelix** [comment]
@dhiller I did not stumble over this again, let's keep it closed for now.
