### ISSUE TITLE
Add s390x prow workload cluster for running e2e tests.

### ISSUE THREAD

**Issue by vamsikrishna-siddu** [kubevirt/project-infra#3540]
Hi @brianmcarey 
As discussed, I have created a new s390x External CI cluster in IBM Cloud to run kubevirt e2e tests for s390x.
I have encrypted the Kubeconfig by following this document and attaching the Kubeconfig here.
https://github.com/kubevirt/project-infra/blob/main/docs/how-to-add-a-prow-cluster.md#how-to-encrypt-the-kubeconfig-of-your-cluster

[s390x-e2e-tests-kubeconfig.tar.gz](https://github.com/user-attachments/files/16328263/s390x-e2e-tests-kubeconfig.tar.gz)

**Comment by brianmcarey** [comment]
Hi @vamsikrishna-siddu ,

I've added the kubeconfig for this cluster - its named as `kubeconfigS390x`

I think we can close this issue?

**Comment by vamsikrishna-siddu** [comment]
> Hi @vamsikrishna-siddu ,
> 
> I've added the kubeconfig for this cluster - its named as `kubeconfigS390x`
> 
> I think we can close this issue?

Thanks @brianmcarey, yeah sure you can close the issue
