### ISSUE TITLE
release-blocker: correct documentation since only root level approvers are allowed to use it

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#3631]
**What happened**:
Whenever the release-blocker acts upon, the comment it attaches says every org member is allowed to use it [1], but that isn't the case - only top level approvers from OWNERS can change the labelling [2]. 

**What you expected to happen**:
The message should clearly have stated that only **top level approvers** can change blocker labels [1]

**How to reproduce it (as minimally and precisely as possible)**:
_-_

**Additional context**:
* line where comment message is generated: [1]

[1]: https://github.com/kubevirt/project-infra/blob/a609d2f66961a57e6a447e29151f44bf6cf14464/external-plugins/release-blocker/server.go#L327
[2]: https://github.com/kubevirt/project-infra/blob/main/external-plugins/release-blocker/server.go#L106

/good-first-issue

**Comment by amha-mersha** [comment]
Hello @dhiller, I would like to take on this issue and work on it.

**Comment by anishbista60** [comment]
@dhiller i haven't seen the top level approver list ? could you help me to locate that ? so , that i can reference the OWNERS.

**Comment by dhiller** [comment]
> @dhiller i haven't seen the top level approver list ? could you help me to locate that ? so , that i can reference the OWNERS.

Hey @anishbista60 , thank you for taking the time looking into this. I've seen your PR and it looks great :tada: !

For future reference:

"Top level approvers" always means the approvers [^1] from the top-level OWNERS file in any of our repositories (Example for kubevirt/kubevirt is here [1] ).

> [!NOTE]
> If you open the link to the file, you'll just see a reference, which implicitly points to the OWNERS_APPROVERS file where the group `approvers` is defined.

FTR - how [OWNERS] files work

[1]: https://github.com/kubevirt/kubevirt/blob/main/OWNERS#L6
[OWNERS]: https://www.kubernetes.dev/docs/guide/owners/

[^1]: An approver in that regard is a KubeVirt org member who effectively can approver a pull request, so that it can get merged.
