### ISSUE TITLE
Sync jobs OWNERS files with OWNERS from source repos 

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#406]
In regard of the topic of automating maintenance of reviewers and approvers for jobs a cron job that syncs the OWNERS file from the repository root to the job directory might be helpful.

Instead of writing sth from scratch we should investigate whether there's a mechanism that takes care of this already that we can borrow. I remember they do sth similar for github.com/openshift/release .

I.e. daily sync from
`https://github.com/nmstate/kubernetes-nmstate/blob/master/OWNERS`
to 
`https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/jobs/nmstate/OWNERS`

@rmohr WDYT?

Part of this issue might be cleaning up the current root OWNERS file.

**Comment by rmohr** [comment]
Works for me.  Is there some tool already which we can just borrow?

**Comment by dhiller** [comment]
Don't know. Maybe add this as part of the issue to investigate if there is sth instead of reinventing the wheel.

**Comment by dhiller** [comment]
They use [autoowners from openshift/ci-tools](https://github.com/openshift/ci-tools/blob/fbe97ab0f8d04d77819c69e52f7bab3db4caa83b/cmd/autoowners/main.go) for that purpose with [this job definition](https://github.com/openshift/release/blob/c368b6cac26b047139bdde9f655468971fb9c442/ci-operator/jobs/infra-periodics.yaml#L596)

**Comment by dhiller** [comment]
PR for autoowners had been merged, now we need to create a periodic job definition to execute this regularly (i.e. daily).

**Comment by rmohr** [comment]
/close

This is implemented.
