### ISSUE TITLE
prow: label-sync cron job is failing

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#477]
Since around 2020-06-09 the [label-sync prow job](https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/templates/label-sync.yaml) fails. 
Error log looks like this:
```
time="2020-06-16T03:16:15Z" level=fatal msg="failed to update nmstate" error="failed to list labels: [status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\ "} status code 404 not one of [201], body:
...
```

Suspicion is that the last config update didn't work somehow, which may be confirmed by this log message from the last successful job run:
```
time="2020-06-07T23:17:19Z" level=warning msg="Repo isn't inside orgs" org=nmstate orgs=kubevirt repo="nmstate/kubernetes-nmstate"
```

Further suspicion is that this is somehow related to the access from prow to the nmstate repositories, which might be indicated by label-sync failing with 404 when trying to list the existing labels.

**Comment by dhiller** [comment]
@phoracek can you check whether `https://github.com/kubevirt-bot` has access to the repositories `nmstate`, `nmstate.github.io` and `ansible-nmstate`? Or should we remove the label-sync for nmstate org?

**Comment by phoracek** [comment]
@dhiller AFAIK we only need the bot in nmstate/kubernetes-nmstate.

@EdDev do you know whether it is used in other repos under nmstate?

**Comment by EdDev** [comment]
> @EdDev do you know whether it is used in other repos under nmstate?

Missed this one, sorry. It is used only by knmstate.
