### ISSUE TITLE
flakefinder: extend number of PRs for which data is presented by adding PRs with /lgtm /approve and in-merge-pool

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#493]
we should also display non-merged PRs which are /lgtm and /approve and entered the merge pool.

**Comment by dhiller** [comment]
/remove-lifecycle rotten
/reopen

we still want to do this

**Comment by rmohr** [comment]
I am uncertain about this. A "live" section may be worth having, but let's ensure that we don't mix them.

**Comment by rmohr** [comment]
I am still not convinced that we want this. It is legitimate that issues occur on batches.

**Comment by dhiller** [comment]
OK. We might rather go for including the periodics.

/close
