### ISSUE TITLE
Periodic job `periodic-test-infra-rotten` is failing and there is no logs at prow.

### ISSUE THREAD

**Issue by qinqon** [kubevirt/project-infra#519]
Periodic job periodic-test-infra-rotten is failing and there is no logs at prow.

job: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-test-infra-rotten/1276398316250206208

**Comment by rmohr** [comment]
/close

There is an infra task on the cluster owners to check this specific VM this ran on. Apart from that the job is running fine. Only one failed run today due to the general github availability issues.
