### ISSUE TITLE
flakefinder omits test failures in daily report that are clearly listed in weekly

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#596]
Example:
Daily: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-08-22-024h.html
Weekly: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-08-22-168h.html

Daily is missing failures from PRs kubevirt/kubevirt#4000, kubevirt/kubevirt#4036, kubevirt/kubevirt#4005

/cc @rmohr @oshoval

**Comment by dhiller** [comment]
Job log is here: https://storage.googleapis.com/kubevirt-prow/logs/periodic-publish-kubevirt-flakefinder-daily-report/1297329223903481856/build-log.txt?Expires=1598444918&GoogleAccessId=prow-46%40kubevirt-240711.iam.gserviceaccount.com&Signature=hKddj%2BP5jxatktnmtPEhPWme8SGLCCfGJYyNJyvCFcdYit1lBrN8lasXGIlSYhx0yHfpgTK9%2FjrsK2a8TtWXGDeUfHSFz%2BAFiiIGTSVkOSqpXo6S3x3JsMuCplWuU%2FVc%2BaOovLS99zIVqQWNuJLg2q9eGJt3NVcfM0O4W58ctiTgLUQIFgmcKp19SoxFyKvsr%2Bwbd3wUkgFX5d4yAEGTeMnKx0YlBwdJe0eoycgUI%2BxModKU68MaP2XyEFPCMFVwGwEGIL1Qw1Z5uQwm6d%2B0TDBWkHXjiHcLrRnpeko9okjCxi420cpscbeZ%2FwvShrhPoeaXoQucnJxBMQHtpWmfHg%3D%3D

**Comment by dhiller** [comment]
What we can see from the log is that test results before the reporting interval are clearly omitted. This creates a between daily and weekly reports where test failures get reported in weekly reports(due to interval including them) while they don't if the test failure occurred before the start of the interval. Even worse, when there's a long running PR event the older test failures (+1w) don't get reported in the weekly, but only in the monthly report (and even then we might miss some failures).

So the mitigation would be to remove the test failure filtering by report interval entirely and report all test failures regardless of when they happened, therefore only the PR merge point in time decides whether a failure gets reported, leading to same report of failures per PR regardless of how long the report interval is.

@rmohr @oshoval makes sense?

**Comment by oshoval** [comment]
Thanks Daniel
