### ISSUE TITLE
[Flaky CI] kubevirt-io-periodic-link-checker "Could not locate Gemfile"

### ISSUE THREAD

**Issue by qinqon** [kubevirt/project-infra#614]
Looks like the retester job is failing at some infra issue

```
`/` is not writable.
Bundler will use `/tmp/bundler20200902-16-1kpi7wh16' as your home directory temporarily.
Could not locate Gemfile
```

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/kubevirt-io-periodic-link-checker/1301068859809206273

/triage build-officer
/kind bug

**Comment by codificat** [comment]
This was fixed a while ago through #615

/close
