### ISSUE TITLE
flakefinder: add list of jobs that were part of the report

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#729]
/kind enhancement

In order to better distinguish flaky tests from cluster failures or other temporary infrastructure issues, we will add a list of the job runs that were part of the report at the top of the report above the table. To avoid overloading the reader in case lots of job runs are part of this report, the list should only be shown on demand, and then in an overlay, i.e.:

```
               jobs v
...------------------
    |   k8s-1.42    | 
...------------------
    |   3/1/2       | 
```

after click on "expand" it might look like this:

```
               jobs v
...------------------------
   1  |  01234567  |  41  | 
   2  |  12345678  |  37  |
      ...
```

where the first number is the job number and the second in braces is the number of failures.

The job number should be href'ed to the prow job run. 

/cc @oshoval

**Comment by oshoval** [comment]
Thanks Daniel,
Jobs would be appended and reserve the order they were added, as the flakes are right?
Its important, because if the watcher review the report again, he can resume from where he stopped

**Comment by dhiller** [comment]
Yes, as the report is generated as static html page there is no change in order.

**Comment by dhiller** [comment]
@oshoval Updated dummy to reflect your proposals, please check whether that matches.

**Comment by oshoval** [comment]
Looks great, thank you
