### ISSUE TITLE
rehearsal: diff seemingly not working properly

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#791]
Context was PR https://github.com/kubevirt/project-infra/pull/694 "create a periodic to publish kubectl-virt-krew package

I ran a rehearsal on the PR. Effect was that not only the new job and the other touched job got run but lots of other jobs also got rehearsed.

**Side node: that the images vanish is a separate story which should also be fixed.**

**Comment by dhiller** [comment]
Accordingly the issue has been fixed already but is not yet rolled out.

**Comment by rmohr** [comment]
Here the PR which fixes this, but not rolled out: https://github.com/kubevirt/project-infra/pull/671
