### ISSUE TITLE
Provide a docker mirror in the setup

### ISSUE THREAD

**Issue by rmohr** [kubevirt/project-infra#90]
We need a docker proxy which can cache often used images within the cluster. @danielBelenky Can you look into this?

**Comment by rmohr** [comment]
The basic mirror is in #89 included and running. I did not check yet if there is something like image rotation, to limit the used space.

**Comment by danielBelenky** [comment]
@rmohr maybe worth splitting the addition of the proxy registry from the addition of the jobs? is this functionality critical for us or a 'best practice'? So far we've worked w/o any specific proxy service but the local storage we have on the `slots` by standard-ci.
