### ISSUE TITLE
flakefinder: automate issue creation

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#949]
We can say that creating an issue for the flakes report generated by the flakefinder is pretty straightforward, therefore we also could just automate it to relieve the build-watcher from this tedious task.

This would then change the build watchers job to each morning look at the created issues and decide how to enact on them.

# Proposal: automate issue creation for flakes

### Pass 1
- separate cluster-failures lanes into separate cluster-failure issues
- for each lane
  - search for an existing issue
    - having `label:triage/build-watcher` and
    - and title equals new issue title
  - if exists
    - reopen issue
    - add comment, including links to failed lane
  - otherwise
    -  create a cluster-failure issue, including links to failed lane

### Pass 2
- for the remaining flakes, for each flake
  - search for an existing issue
    - having `label:triage/build-watcher` and
      - either test has `test_id:[0-9]+' 
      - or full search for test name)
  - if exists
    - reopen issue
    - add comment, including links to failed lanes
  - otherwise
    - create new issue with links to failed lanes

## Parameters:
- create-flake-issues=true (default false)
- create-flake-issues-labels=triage/build-watcher,type/bug,sig/compute
- create-flake-issues-threshold=0/30 (0 meaning create issue for every found flake)
- failure-threshold-for-suspected-cluster-failure=50 (note: only if the failures all occurred in any one lane

**Comment by fgimenez** [comment]
Not sure if it is implied in the description, just wanted to mention that we should also check the periodic e2e from master lanes https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml#L414-L518 not only presubmits.

**Comment by fgimenez** [comment]
I think the bot should also take care of reopening closed issues in case of new failures.

**Comment by dhiller** [comment]
> I think the bot should also take care of reopening closed issues in case of new failures.

Good point, will add this to the issue.

Besides that: how about tackling the extension to cover periodics also in another issue? I figure this might be a bigger topic...

**Comment by dhiller** [comment]
> Not sure if it is implied in the description, just wanted to mention that we should also check the periodic e2e from master lanes https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml#L414-L518 not only presubmits.

Good point, there's also the periodics running on openshift ci (u/s and d/s) that might also contain valuable data!

**Comment by fgimenez** [comment]
> Besides that: how about tackling the extension to cover periodics also in another issue? I figure this might be a bigger topic...

Totally agree :+1:

**Comment by dhiller** [comment]
FYI: the first run against kubevirt/kubevirt would have created 13 issues and reopened 3 existing ones:

```bash
$ grep -E '(Create|Reopen) issue' build.log | grep -oE '((Create|Reopen) issue:) .*Title:.* State:' | sed -E 's/((Create|Reopen) issue:) .*Title:(.+) State:/# \1 \3/'
# Create issue: [flaky ci][rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Creating a VirtualMachineInstance with non default namespace [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]should log libvirt start and stop lifecycle events of the domain [test_id:1641]kubevirt-test-default
# Create issue: [flaky ci][rfe_id:151][crit:high][vendor:cnv-qe@redhat.com][level:component]CloudInit UserData [rfe_id:151][crit:medium][vendor:cnv-qe@redhat.com][level:component]A new VirtualMachineInstance with cloudInitConfigDrive networkData [test_id:4622]should have cloud-init meta_data with tagged devices
# Create issue: [flaky ci][Serial][rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration Starting a VirtualMachineInstance  rook-ceph live migration cancelation [test_id:3241]should be able to cancel a migration right after posting it
# Reopen issue: [Flaky CI][Serial][rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] should block the eviction api and migrate
# Reopen issue: [flaky CI] pull-kubevirt-e2e-k8s-1.16 [rfe_id:3064][crit:medium][vendor:cnv-qe@redhat.com][level:component]Pausing A valid VM when paused via virtctl [test_id:3226]should be restarted successfully into unpaused state
# Create issue: [flaky ci][Serial][rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration Starting a VirtualMachineInstance  with setting guest time [test_id:4114]should set an updated time after a migration
# Create issue: [flaky ci][rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Creating a VirtualMachineInstance [test_id:3196]should carry kubernetes and kubevirt annotations to pod
# Create issue: [flaky ci][rfe_id:127][posneg:negative][crit:medium][vendor:cnv-qe@redhat.com][level:component]Console [rfe_id:127][posneg:negative][crit:medium][vendor:cnv-qe@redhat.com][level:component]A new VirtualMachineInstance without a serial console [test_id:4117]should not have the  serial console in xml
# Create issue: [flaky ci][rfe_id:127][posneg:negative][crit:medium][vendor:cnv-qe@redhat.com][level:component]Console [rfe_id:127][posneg:negative][crit:medium][vendor:cnv-qe@redhat.com][level:component]A new VirtualMachineInstance with a serial console with a fedora image [test_id:1589]should return that we are running fedora
# Reopen issue: [Flaky CI] [Serial][rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration Starting a VirtualMachineInstance rook-ceph live migration cancelation should be able to cancel a migration [test_id:2226] with ContainerDisk
# Create issue: [flaky ci][Serial]Infrastructure [rfe_id:4102][crit:medium][vendor:cnv-qe@redhat.com][level:component]certificates [test_id:4099] should be rotated when a new CA is created
# Create issue: [flaky ci][Serial]SRIOV VirtualMachineInstance with sriov plugin interface [test_id:3957]should connect to another machine with sriov interface over IPv6
# Create issue: [flaky ci]Configurations VirtualMachineInstance definition [rfe_id:3078][crit:medium][vendor:cnv-qe@redhat.com][level:component]with usb controller [test_id:3117]should start the VMI with usb controller when input device doesn't have bus
# Create issue: [flaky ci][rfe_id:127][posneg:negative][crit:medium][vendor:cnv-qe@redhat.com][level:component]Console [rfe_id:127][posneg:negative][crit:medium][vendor:cnv-qe@redhat.com][level:component]A new VirtualMachineInstance with a serial console [test_id:1591]should close console connection when new console connection is opened
# Create issue: [flaky ci][rfe_id:3064][crit:medium][vendor:cnv-qe@redhat.com][level:component]Pausing A valid VMI when paused via API [test_id:4597]should signal paused state with condition
# Create issue: [flaky ci][Serial]IOThreads IOThreads Policies [test_id:4122]Should honor shared ioThreadsPolicy for single disk
```

See https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-flake-issue-creator/1374880155595444224 for details.
